services:
  - type: web
    name: permission-militaire
    runtime: docker
    dockerfilePath: ./Dockerfile.prod
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true

databases:
  - name: db-permission
    databaseName: militaire_db
    user: militaire_user
    plan: free
